platform :ios, '8.0'
use_frameworks!

target 'MZDownloadManager_Example', :exclusive => true do
  pod 'MZDownloadManager', :path => '../'
end

target 'MZDownloadManager_Tests', :exclusive => true do
  pod 'MZDownloadManager', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
