platform :ios, '9.0'
use_frameworks!

target 'MZDownloadManager_Example' do
  pod 'MZDownloadManager', :path => '../'
end

target 'MZDownloadManager_Tests' do
  pod 'MZDownloadManager', :path => '../'

  
end
